### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by ilyaguy** [shtange/bushed-bricks#1]
Game does not fit to display neither portrait nor landscape orientation.
Smartphone display with 1280x720 resolution.

**Comment by shtange** [comment]
Done. The game is displayed correctly on the mobile devices.
For example, on 720x1280 looks like this:
![screenshot_game_mobile_720x1280](https://cloud.githubusercontent.com/assets/3062509/21990276/d6c9f4da-dc16-11e6-889a-a0bb14200155.jpg)
