### ISSUE TITLE
Too easy winning strategy

### ISSUE THREAD

**Issue by aromanovsky** [shtange/bushed-bricks#2]
The game is unbalanced. A simple input loop (up, left, down, right) allows to play the game infinitely. The field stays at least 50% free all the time and the average outflow balances average inflow.

Numbers don't affect this winning strategy at all.

**Comment by shtange** [comment]
Looks like this was solved. Commit [#79f583a ](https://github.com/shtange/bushed-bricks/commit/79f583a2d164038c901b176bc40ccd6c419c52df)

**Comment by aromanovsky** [comment]
The way the issue is fixed is one of the best possible reasons not to play.

**Comment by shtange** [comment]
This is a temporary solution. I'll be back to that.
The project is open, you can offer your solution. If you know how best, please join us.
