### ISSUE TITLE
Suggestion for block operations priority

### ISSUE THREAD

**Issue by igurkina** [shtange/bushed-bricks#4]
There is some inconsistency with priority of block combining and removing. 
Usually in such games block combining has higher priority, than other operations. Thus I'd expect on 'Down' action that two blue blocks selected on 'step_1.png' screenshot would combine to blue block with '8' level, and then this block would move to blue line. Instead, block with '7' level is moved to blue line (removed from main game field), and single block is just shifted a bit.
E.g. see attached screenshots (pay attention to block in red frame).

![step_1](https://cloud.githubusercontent.com/assets/8073498/21989355/415119e0-dc13-11e6-8a2c-e457301f55df.png)
![step_2](https://cloud.githubusercontent.com/assets/8073498/21989356/4152f4b8-dc13-11e6-98cf-1c228a1e5ff0.png)

**Comment by shtange** [comment]
Done. The priority of the combination process has been increased. But I'm not sure that this is right. Waiting for feedback by players...

Thank you for your participation!

**Comment by igurkina** [comment]
Probably, it would be better just to switch actions priorities?
Current change does both actions (combining 2 blocks and removing them) within one move. It might be less confusing if this action was done in separate moved. For the case above: 'Down' move -> 2 blocks combine making one '8' level blue block -> 'Down' move -> '8' level blue block is moved to blue line (removed).

**Comment by shtange** [comment]
That's a great idea. I've implemented it. So much better. Thank you.
